LOCALIZED_TEXT = 'LOCALIZED_TEXT'
MODIFIED = 'MODIFIED'
NODE = 'NODE'
TEXT = 'TEXT'
BUILTIN = 'BUILTIN'
CREATED = 'CREATED'
DETAILS = 'DETAILS'
LINK = 'LINK'
NOTE = 'NOTE'
ID = 'ID'
ICONS = 'ICONS'

# Connection

SOURCE_LABEL = 'SOURCE_LABEL'
MIDDLE_LABEL = 'MIDDLE_LABEL'
TARGET_LABEL = 'TARGET_LABEL'
STARTINCLINATION = 'STARTINCLINATION'
ENDINCLINATION = 'ENDINCLINATION'
